### ISSUE TITLE
Is this plugin still working ?

### ISSUE THREAD

**Issue by mcarpentier** [topicusonderwijs/m2e-settings#1]
hello Martijn,
Is this plugin still working ?
I'm using the latest spring STS (based on Eclipse Mars.2 (4.5.2)) and i'm used to eclipse:eclipse.
Now i'd like to switch to m2 so i followed ur instructions but my files aren't copied in the .setings directory of my project.
Nothing special in my pom.xml config, it's just as your documentation : 

``` xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-eclipse-plugin</artifactId>
                <version>2.9</version>
                <dependencies>
                    <dependency>
                        <groupId>com.mycompany.conf</groupId>
                        <artifactId>config-dev</artifactId>
                        <version>1.2.1</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <additionalConfig>
                        <file>
                            <name>.settings/org.eclipse.jdt.core.prefs</name>
                            <location>eclipse/org.eclipse.jdt.core.prefs</location>
                        </file>
                        <file>
                            <name>.settings/org.eclipse.jdt.ui.prefs</name>
                            <location>eclipse/org.eclipse.jdt.ui.prefs</location>
                        </file>
                    </additionalConfig>
                </configuration>
            </plugin>
```

Whereas when i use mvn eclipse:eclipse on this pom everything works fine, my 2 files are copied in the .settings dir

Any idea ?

**Comment by dashorst** [comment]
It works in our systems, but we don't use STS. I use 4.5.2 (Mars 2) with a stripped down Java EE profile (built up from Eclipse for Java devs)

**Comment by mcarpentier** [comment]
Still not working with Eclipse 4.5.2,  would you by chance have a working project example ?

**Comment by dashorst** [comment]
One open source project I know that uses the plugin and setup is:

https://github.com/apache/wicket 

It's not too big a project so easy to import and see the modifications.

**Comment by mcarpentier** [comment]
Hey Martijn,
Finally got some time to work on it and find the problem
I had the maven-eclipse-plugin configuration in the plugin section of the build, which does not work.
I did like they did on wicket and put the configuration of the plugin under pluginManagement.
Works fine now
Thanks for your help

**Comment by dashorst** [comment]
👍
